var pcinfo= {
  pc1:{
    pcname: 'Macbook Pro 13 inch',
    display:' LED backlit, 2560 x 1600',
    cpu:'2.3GHz dual-core Intel Core i5',
    ram:'8GB of LPDDR3',
    motherboard:'Macbook specific motherboard',
    gpu:'Intel Iris Plus Graphics 640',
  },
  pc2:{
    pcname: 'Microsoft Surface Pro',
    display:'PixelSense™ Display, 2736 x 1824',
    cpu:'	Intel® Core™ 7th-generation m3, i5, or i7',
    ram:'4, 8 or 16 GB',
    motherboard:'Surface Pro specific',
    gpu:'Intel® HD Graphics 620 (i5)(one of three options)',
  },
  pc3:{
    pcname: 'Alienware 13',
    display:'2560 x 1440 OLED',
    cpu:'Up to Intel® Core™ i7-7700HQ',
    ram:'Up to 32GB DDR4',
    motherboard:'Alienware specific',
    gpu:'NVIDIA® GeForce® GTX 1060 with 6GB GDDR5',
  },
  pc4:{
    pcname: 'iMac 2017 4k',
    display:'Retina 4k, 4096 x 2304',
    cpu:'3.0GHz quad‑core Intel Core i5',
    ram:'8GB of DDR4',
    motherboard:'iMac specific',
    gpu:'Radeon Pro 555 with 2GB of VRAM',
  },
  pc5:{
    pcname: 'Alienware X51',
    display:'Dependant on Monitor',
    cpu:'3.1 GHz Intel Core i5 (3rd Gen) 3450',
    ram:'8GB DDR3',
    motherboard:'LGA1155 Socket',
    gpu:'NVIDIA GeForce GT 640',
  },
  pc6:{
    pcname: 'iBuyPower AMD Ryzen 7X configuration',
    display:'Dependant on Monitor',
    cpu:'AMD Ryzen 7 1700X',
    ram:'8GB DDR4',
    motherboard:'GIGABYTE AX370 Gaming',
    gpu:'GeForce GTX 1060 3GB',
  },
}
